agent_model:
  name: Qwen/Qwen3-4B-Instruct-2507
  type: qwen
  temperature: 0.6
  top_p: 0.6
  top_k: null
  max_length: 2048
  dtype: bf16

agents: null

critic_model:
  name: Qwen/Qwen3-4B-Instruct-2507
  type: qwen
  max_length: 2048
  dtype: bf16

critics: null

seed: 42

dataset:
  name: str_build
  type: str_build
  train_split: '[:8]'
  eval_split: '[8:]'
  csv_path: ../dataset/data.csv
  local_z: 0
  spacing: 2

prompt:
  use_chat_template: true
  provide_graph: false

task:
  max_commands: 300
  block_agent1:
  - oak_planks
  - stone
  - air
  block_agent2:
  - white_concrete
  - obsidian
  - air

output:
  base_dir: output_maac_str_build
  verbose: false
  save_final_model: false
  save_path: output_maac_str_build

external:
  mode: position_feedback
  original_prompt: true
  previous_response: true
  external_prompt_passthrough: false

maac:
  parallel_training: none
  agent_devices:
  - cuda:0
  critic_devices:
  - cuda:0
  num_agents: 2
  num_turns: 4
  critic_type: v
  num_train_epochs: 150
  agent_learning_rate: 2.5e-06
  critic_learning_rate: 2.5e-06
  value_loss_coef: 0.6
  rollout_buffer_size: 1
  train_batch_size: 1
  max_new_tokens: 512
  discount: 0.9
  early_termination_threshold: -0.1
  eval_interval: 10
  eval_num_samples: 2
  eval_batch_size: 1
  logging_steps: 20

reward_processor:
  enabled: true
  scale_factor: 1.0
  shift: -2.0

wandb:
  project: str_build
  entity: OpenMLRL
  run_name: str_build_maac
  dir: output_maac_str_build
  tags:
  - maac
  - str_build
